### ISSUE TITLE
タイトルとカテゴリーに`#`が含まれている記事をpullした時の不具合

### ISSUE THREAD

**Issue by tnk4on** [basd4g/gimonfu#19]
記事のタイトルとカテゴリーが下記のような場合に、pull時にデータが置き換わることが分かりました。

- 元データ
```
title: TEST Meetup #3 - テスト
categories:
  - #test
  - イベント
```

- pull後
```
title: TEST Meetup
categories:
  - null
  - イベント
```

イベントのナンバリングやハッシュタグを使用する場合などに`#`を使用するので、対応いただけるとありがたいです。
各種セットアップは[Qiitaの記事](https://qiita.com/yammerjp/items/1a38857f6bafb20f065d)を参考にさせて頂きました。

**Comment by yammerjp** [comment]
gimonfuを使っていただき、また問題を報告いただきありがとうございます。
ご指摘の通りタイトルやカテゴリ名にハッシュ (#) が入っていると正しく動作していませんでした。

暫定的に修正して公開しましたので、新しいバージョンのv0.2.2  (https://github.com/yammerjp/gimonfu/releases/tag/v0.2.2) をお使いください。

なお修正後のバージョンを利用される際、ハッシュを含むタイトルやカテゴリ名の記事をファイル上で作成・修正する場合、その**文字列全体をダブルクオーテーション (") で囲ってください**。
具体的には以下の例のようにファイルに記述してください。

```
title: "TEST Meetup #3 - テスト"
categories:
  - "#test"
  - イベント
```

はてなブログのWebサイト上でタイトルやカテゴリ名にハッシュ (#) を含む記事を作成・編集した場合は、`gimonfu pull`の際に自動でダブルクオーテーションで囲まれるようになります。

不明点や疑問、問題などが有りましたらまたご連絡ください。
よろしくお願いします。

**Comment by yammerjp** [comment]
上述のバグの経緯について記録のために記述します。
(アプリケーションの利用に必要な情報ではなく、開発のための備忘録です。)

gimonfuは記事のメタデータを記述するために記事ファイルの先頭にYAML形式で情報を付加しています。YAMLでは、文字列中にハッシュ (#) があると、ハッシュ以降行末までをコメントとして扱い無視する仕様があります。

https://yaml.org

`gimonfu pull`する際は本来はハッシュがコメントアウトとして認識されないよう文字列全体をダブルクオーテーション (") で囲む必要がありましたが、それが成されていませんでした。

gimonfuはpushの際もpullの際も変更があったファイルを上書きするため、pushでもpullでもハッシュを含んだ文字列を書き出すすべての場合でこの問題の影響が発生し、誤った形式でファイルが上書きされます。

結果として、ハッシュのついた記事をpush又はpullした後に再度pullするとき、文字列中のハッシュがコメントアウトとして認識されて削除されてしまいます。

このような問題を防ぐためにはYAMLの出力はYAMLのライブラリ (本プロジェクトで用いている front-matter やそれが用いている js-yaml) を通して扱うべきで、今後の課題とします。

**Comment by tnk4on** [comment]
対応ありがとうございます！実サイトでの動作も想定通りのものとなっていました。とても助かりました。

> なお修正後のバージョンを利用される際、ハッシュを含むタイトルやカテゴリ名の記事をファイル上で作成・修正する場合、その文字列全体をダブルクオーテーション (") で囲ってください。

今後はこの点を忘れないように使用いたします。
素早い対応ありがとうございました！
