### ISSUE TITLE
gimonfu pullにおけるエラー

### ISSUE THREAD

**Issue by shinGangan** [basd4g/gimonfu#8]
github actionsにおいてgimonfuを使用しています。
<code>npx gimonfu --git-commit-date pull</code>の実行時に下記エラーに遭遇しました。

```
incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 1, column 65:
     ... kages due to an EnvironmentError: [Errno 13] Permission denied:  ... 
                                         ^
Error: Process completed with exit code 255.
```

原因としては、タイトルに<b>：</b>が入っていることのようでした。
pull時の問題なのでpackage側で対応頂けると幸いです。

**Comment by yammerjp** [comment]
gimonfuを使っていただき, また bug の報告をしてくださりありがとうございます :)

ご指摘の通り, タイトルに : (コロン) が入っていると pull に失敗していたので, タイトルを " (ダブルクオーテーション) でくくってファイルに出力するように修正しました.

もし既に記事タイトルにコロンが含まれているマークダウンファイルがありましたら, 記事タイトルをダブルクオーテーションで括る形に変更していただけるとよいかと思います.

**Comment by shinGangan** [comment]
早急な対応に感謝いたします．
GitHub Actionsで連携しやすいため，今後ともgimonfuを利用していこうと思っております．

下記対応について，こちらの方でも試してみようと思います．
> もし既に記事タイトルにコロンが含まれているマークダウンファイルがありましたら, 記事タイトルをダブルクオーテーショ> ンで括る形に変更していただけるとよいかと思います.
